export const RECORD_USERINFO = 'RECORD_USERINFO';
export const GET_USERINFO = 'GET_USERINFO';
export const RECORD_SHOPINFO = 'RECORD_SHOPINFO';
export const GET_SHOPINFO = 'GET_SHOPINFO';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';